version: '3.8'

services:
  # MySQL Production Database Service
  ezmovie-db:
    image: mysql:8.0
    container_name: ezmovie-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-123456}
      MYSQL_DATABASE: ${DB_DATABASE:-ezmovie}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ezmovie-network

  # NestJS Production Backend Service
  ezmovie-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ezmovie-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_TYPE=mysql
      - DB_HOST=ezmovie-db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-123456}
      - DB_DATABASE=${DB_DATABASE:-ezmovie}
      - JWT_SECRET=${JWT_SECRET:-super-secret-key-123}
      - JWT_EXPIRES_IN=1d
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=${MAIL_USER:-thaiduongdiep@gmail.com}
      - MAIL_PASS=${MAIL_PASS:-qhwynjupzqwjgpwd}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-262276831455-9ipepm6vngf6c4gf4u81fnh5o1qjgeee.apps.googleusercontent.com}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-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}
      - GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback
      - FRONTEND_URL=http://localhost:4200
    depends_on:
      - ezmovie-db
    networks:
      - ezmovie-network

volumes:
  mysql-data:
    driver: local

networks:
  ezmovie-network:
    driver: bridge
